### ISSUE TITLE
Compilation without GL context

### ISSUE THREAD

**Issue by joSartek** [NVIDIA/NvPipe#14]
Hi,
I have been using NvPipe for some time to encode and stream images from a cluster. 
Since the last update of the library, I can no longer compile it on the cluster because it requires an openGL configuration and no graphical environment is installed on the machine. How can I compile NvPipe again on a cluster without any graphical environment?

I will take this opportunity to ask another question.
Before the update, it was possible to specify the path of the Video Codec SDK but there is no more this option at compile time. Is the SDK directly integrated into NvPipe?

**Comment by tbiedert** [comment]
Hi,
thanks for your valuable feedback!

Can you please post the compiler error you‘re getting?

Also, can you please post more information on your environment (OS, compiler, driver, etc.)?

Regarding your second question:  before the update, there was an older version of the encode API header included. The Video Codec SDK path option made CMake try to copy a newer version from a subdirectory of the path specified. However, since that path changed with a newer Video Codec SDK version, instead of adding switch statements, we decided to directly include a slightly newer header file directly with NvPipe. 

Other than that, NvPipe was redesigned based on the novel reusable NvCodec classes in Video Codec SDK 8.1 to enable more usecases than the deprecated version (HEVC, integer frames, lossless compression, OpenGL interface).

We would love to hear more about your usecases of NvPipe for hardware-accelerated remote streaming. Feel free to reach out at tbiedert@nvidia.com.

**Comment by joSartek** [comment]
Thank you for your answer.

I use gcc 5.4 and NVCC for cuda 8.0 on a CentOS 7.x and the Nvidia Driver 390.48.

The compiler error is a simple "file not found error" for GL/gl.h :
**In file included from /.../nvpipe/src/NvPipe.cu:48:0:
/opt/cuda/8.0/include/cuda_gl_interop.h:67:19: fatal error: GL/gl.h: Aucun fichier ou dossier de ce type**

No graphics environment is configured on this machine (Nvidia Quadro VCA) and I do not want (if possible) to use tools like EGL.
The buffer I encode is a simple pointer allocated on the GPU and results from a CUDA kernel. Is it possible to compile NvPipe without any dependency with OpenGL?

**Comment by tbiedert** [comment]
Thanks!  I will add a CMake option to disable the OpenGL interface (by next week probably).

**Comment by joSartek** [comment]
Thank you very much for your responsiveness ! This solution suits me perfectly !

**Comment by tbiedert** [comment]
I've added the CMake option `NVPIPE_WITH_OPENGL`. Please let me know if this solves your issues!

**Comment by fcladera-n** [comment]
Hello @tbiedert, I am getting the following error related with GL

```
In file included from /home/nvidia/NvPipe/src/NvPipe.cu:50:0:
/usr/local/cuda-9.0/include/cuda_gl_interop.h:64:2: error: #error Please include the appropriate gl headers before including cuda_gl_interop.h
 #error Please include the appropriate gl headers before including cuda_gl_interop.h
  ^
CMake Error at NvPipe_generated_NvPipe.cu.o.cmake:207 (message):
  Error generating
  /home/nvidia/NvPipe/build/CMakeFiles/NvPipe.dir/src/./NvPipe_generated_NvPipe.cu.o
```

I am trying to compile NvPipe in a Jetson TX1 board.

Thank you!

**Comment by tbiedert** [comment]
Hi, thanks for reaching out!
I'm afraid Video Codec SDK (and thus NvPipe) is not available on the Jetson platform.

Please refer to the [Video Encode and Decode GPU Support Matrix](https://developer.nvidia.com/video-encode-decode-gpu-support-matrix) for more information on supported platforms.
