### ISSUE TITLE
Porting to new NvPipe: R and B channels swapped?

### ISSUE THREAD

**Issue by renewagner** [NVIDIA/NvPipe#35]
Hi all,

could it be that the new NvPipe actually expects input to be BGRA rather than RGBA? I forgot to mention this earlier because it was easy for me to work around by swapping the R and B channels after decoding (in software; using FFMPEG).

In hindsight, this might also play a role in #34 as swapping after decoding is not the same if the encoder applies psycho-visual tricks...

Cheers,

Rene

**Comment by tbiedert** [comment]
Hi,
yes, you are right. The order is in fact BGR. 

In the NvPipe overhaul I was trying to use as much functionality from the official Video Codec SDK as possible. The BGR format is dictated by NVENC's format for direct RGB channel support (instead of YUV), and the color conversion kernel provided by the NvCodec reusable classes.

I will rename NvPipe's format enumeration to make this clear.  

Thanks!
Tim

**Comment by renewagner** [comment]
Hi Tim,

hmm, is there any way to get OpenGL to store textures in BGRA format? I'd like to avoid the overhead of an extra CUDA kernel launch just to do the conversion...

Cheers,

Rene

**Comment by tbiedert** [comment]
I assume you’re already using some OpenGL fragment shader to write the color buffer / texture attachment?  Then you could directly swizzle the components.

**Comment by tbiedert** [comment]
I've just pushed an update to Video Codec SDK 9, which includes proper YUV -> RGBA conversion.
