### ISSUE TITLE
No frame decoded (Decoder expects encoded bitstream for a single complete frame. Accumulating partial data or combining multiple frames is not supported

### ISSUE THREAD

**Issue by yanpaioo** [NVIDIA/NvPipe#36]
Hi there,

I am encountering the error as mentioned in the title. I'm using DRIVE PX2 to encode and a PC with Pascal GPU to decode. DRIVEWORKS on PX2 doesn't allow to change how it encodes for complete frames. So, will multiple-frame as complete frame decoding in NvPipe be supported in future?

**Comment by hoene** [comment]
yes, I can confirm this bug.
It happens, if the decoder is stopped in between the decoding process. 
If you when call it again, the the previous state thems to be valid. Maybe a decoder reset is needed.

**Comment by tbiedert** [comment]
Hi, thanks for reaching out!

The behavior you're seeing comes from NvPipe's original usecase in one in-one out interactive streaming with NvPipe on both server and client side.

The decoder currently works as follows:
```c++
    uint8_t* decode(const uint8_t* src, uint64_t srcSize)
    {
        // ... decode via NvCodec

        if (numFramesDecoded <= 0)
        {
            throw Exception("No frame decoded (Decoder expects encoded bitstream for a single complete frame. Accumulating partial data or combining multiple frames is not supported.)");
        }

        return decodedFrames[numFramesDecoded - 1];
    }
```

In summary:
(1) The newest frame in case the decoder produced several complete frames
(2) The error you're seeing if the decoder did not produce a full frame as output

If the encoded bitstream is produced by some other encoder such as NvMedia, there might be configuration options (or manual bitstream adjustments) in order to create a sequence of frame packets that encorce an immediate decoding per frame in NvPipe. Since NvPipe is simply using the NvCodec classes provided by the Video Codec SDK under the hood, the official [Video Codec SDK forums](https://devtalk.nvidia.com/default/board/244/video-codec-sdk) would be the best place to get help here.

On the NvPipe side it would be easily possible to adjust the decoding interface such that instead of throwing an exception it just returns the number of frames decoded. If no frame is decoded, you just have to continue feeding more partial data into the decoder until you eventually get your frame. You can actually do this already by just catching the exception. There are currently no plans to decode a sequence of frames with a single decode call, as you can basically achieve the same result with multiple decode calls.

Best
Tim
