### ISSUE TITLE
Browser integration

### ISSUE THREAD

**Issue by straaljager** [NVIDIA/NvPipe#68]
Hello,

we've been using NvPipe to stream remotely rendered visualization to a display GPU, which works amazingly well. We now want to integrate video streaming with NvPipe into our web application to provide a better user experience for users on low-bandwidth connections. So far, I have found a framework named BroadwayJS (https://github.com/mbebenita/Broadway), but I was wondering if there are any others we can use?

**Comment by tbiedert** [comment]
Hey, thanks for the positive feedback!

Broadway.js has been successfully used with NvPipe in the past, e.g., in Benjamín Hernández's SIGHT project: https://github.com/benjha/Sight_FrameServer
However, as a pure software decoder Broadway.js is quite slow.

You can also manually wrap the produced H.264 bitstream in an MP4 container, and stream the wrapped packages via WebSockets to a JavaScript client that uses Media Source Extensions to feed the data into a standard HTML video tag.  The browser can then use hardware-accelerated decoding under the hood.

To produce a valid MP4 stream that can be consumed by the browser, you first need to produce the overall MP4 header which contains some info on the video stream such as codec, resolution, frame rate etc., and then you wrap each H.264 frame behind a small MP4 per-frame header. I suggest checking the MP4 specification. 

Note that you need to implement some flow control on the server side, as the browser will try to play the stream at the constant specified frame rate. Just make sure that the server doesn't render/send frames faster, otherwise the browser will start buffering.  On the contrary, try to stay close to a buffer underrun at all times.

We have a working internal prototype of this approach, that we could share with you under NDA. If this is an option for you, please feel free to reach out directly via tbiedert@nvidia.com.

**Comment by straaljager** [comment]
Thanks for the detailed explanation. I will email you when we have further requests or want to try your prototype.

Thanks!
